apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hf-token-secret
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "vllm-cluster/hf-token"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: hf-token
      type: Opaque
      data:
        - objectName: "vllm-cluster/hf-token"
          key: HF_TOKEN
